### PR TITLE
Add a configuration item for character encoding

### PR DESCRIPTION
**Pull request by astral1**
I add some code for character encoding configuration to "embedded-api". because this use for asian language(IndexEngineCJKAnalyzer or Lucene KoreanAnalyzer etc.). the config key named "encoding". please change it at will, if necessary.

### CODE REVIEW

**Comment by iladriano** [comment]
Thanks! Maybe we can add a new abstract class (extending Action) performing the set character encoding?

**Comment by astral1** [comment]
Of course, It seems like a better solution. I appreciate the flowing commit also added.

**Comment by santip** [comment]
It looks like you've coverted all the newlines in EmbeddedIndexEngine to windows format and the diff is not showing properly. Can you please fix that?

**Comment by astral1** [comment]
All your suggestions were applied and squash all commits in branch.

**Pull request merged**
